Public Enum QueryTableType
    GENRE_QUERY_TABLE
    PUBLISHER_QUERY_TABLE
    AUTHOR_QUERY_TABLE
    CLASSIFICATION_QUERY_TABLE
    DONATOR_QUERY_TABLE
    SUPPLIER_QUERY_TABLE
    YEARLEVEL_QUERY_TABLE
    SECTION_QUERY_TABLE
    LANGUAGE_QUERY_TABLE
    STUDENT_QUERY_TABLE
    FACULTY_QUERY_TABLE
    ADMIN_QUERY_TABLE
    DEPARTMENT_QUERY_TABLE
    LANGUAGES_QUERY_TABLE
    BOOK_QUERY_TABLE
End Enum
