Public Enum QueryTableType
    GENRE_QUERY_TABLE
    PUBLISHER_QUERY_TABLE
    AUTHOR_QUERY_TABLE
    CLASSIFICATION_QUERY_TABLE
    DONATOR_QUERY_TABLE
    SUPPLIER_QUERY_TABLE
    YEARLEVEL_QUERY_TABLE
    SECTION_QUERY_TABLE
End Enum
